### PR TITLE
Kb scenario updates

### PR DESCRIPTION
**Pull request by katieb1**
* All updates in datasheet_raster branch (see [pull request](https://github.com/syncrosim/pysyncrosim/pull/5))
* First argument is parsed as sid if integer
* Can now input lists into the name and sid arguments
* Added copy_external_inputs argument to the run() method to mirror new rsyncrosim enhancement

### CODE REVIEW

**Comment by shreeramsenthi** [comment]
Updates over the previous PR look good! Once the comments in the other PR are resolved this should be good to merge!

**Comment by shreeramsenthi** [comment]
Regarding the comments from the previous PR:
1. Scenarios are returning DataFrames because of `summary = True`, explicitly setting it to false fixes the behaviour issues I was seeing. I think the work around here would be to disregard summary if scenario name or sid is provided? Here's a working example:

> `import pysyncrosim as ps
> 
> myLibrary = ps.library("test.ssim")
> myProject = myLibrary.projects("example project")
> myScenario = myProject.scenarios("example scenario")
> 
> myScenario2 = myProject.scenarios("example scenario", summary = False)
> 
> type(myScenario)
> type(myScenario2)`

2. When I try to filter_columns in datasheet_raster to access rasters that are not in a "*.temp" folder, I'm getting an error on line 622 of library.py because `tempfile_path` is being called without being assigned. `tempfile_path` is only ever assigned in the `except` clause, so this will fail if the `try` statement doesn't raise an exception. I'm not sure how you'd like to fix this. Maybe lines 622 and 623 should just be in the `except` clause and not the `finally`?

**Comment by katieb1** [comment]
I'm just running the package through pytest and fixing up the tests before I make my next commit, but #1 will definitely be fixed in the nextcommit. I've made it so that summary is None by default now and is assigned True or False based on whether a name or sid is included. This is overridden if the user explicitly sets summary to True or False. 

As for #2, that should be an easy fix that I can also make in the next commit!

**Comment by colindaniel** [comment]
Hi Katie – I think it would be best to make the behaviour with respect to defaults regarding summary=True the same in pysyncrosim as they currently are in rsyncrosim. I can’t recall exactly how it all works right in now in rsyncrosim but there is some history behind the decisions that were made. Does this make sense? Are we doing the same thing in both packages? Colin

**Comment by katieb1** [comment]
Hi Colin,

I think in this case it is quite different from rsyncrosim since `scenarios()` is a method of a Library or Project, and you can use the `scenarios()` method to either retrieve a dataframe of all the scenarios (i.e. summary = False) or retrieve a specific scenario instance (i.e. summary = True). With rsyncrosim, you would just use the `scenario()` function to create or retrieve a Scenario, or you would use the `ssimLibrary()` or `project()` functions with name set to the Scenario to get the dataframe. `ssimLibrary()` and `project()` have a summary argument that is set to `NULL` by default, then set to TRUE or FALSE within the code depending on the other arguments. So it does seem that we are doing similar things in both packages.

Katie

**Comment by colindaniel** [comment]
Perfect – thanks!

**Comment by katieb1** [comment]
Ok, those two bugs should be fixed now! Let me know if everything works okay for you now @shreeramsenthi

**Comment by shreeramsenthi** [comment]
Thanks Katie! The scenarios behaviour looks perfect, and I'm no longer getting the datasheet_raster error with filter_columns, but the filtering doesn't appear to be happening.

Sorry I don't have a portable example, but I think the issue has something to do with the indentation of lines 626-629 in library.py. I think this is the only place where the datasheet is filtered by `col` and `col_id` (which are parsed from the `filter_column` argument), and since it is in an `except` block it would only ever get called if `col_id` is not an integer (the `try` block on line 576). Any ideas? Let me know if you can't reproduce the issue and I'll get an example together for you.

**Comment by katieb1** [comment]
Hey Shree, I don't think lines 626-629 should be the issue because all that code has to do with if a string is input into the filter_column argument rather than an integer. The actual filtering takes place at the SyncroSim level, so this code is just grabbing the corresponding column ID for a column string so that it can pass on the integer ID to the SyncroSim call. What are you inputting into the filter_column argument in the function? It should be a string phrase like "TransitionGroupID=20". Maybe this will be too confusing for the users though, and instead there should be two arguments, like "filter_column" and "filter_value"?

**Comment by shreeramsenthi** [comment]
Sounds good, thanks Katie! For reference I'm trying to filter `stsimsf_OutputStockGroup` with "StockGroupID=420" (the stock group ID's are conveniently encoded in the file name). I also tried "Timestep=2021" and got the full stack of rasters in the datasheet both times. Since I am getting rasters back I assume the issue is not that the library is not in the working directory with files in the *.output folder.

Also, this is probably a feature for later, but do you think it would be possible to implement more advanced filtering? For example filtering by multiple columns, or allowing values in lists, etc? I'm probably missing something here, but maybe we could do the filtering that happens in SyncroSim in python using `pandas.DataFrame.query()`? That we we won't need to make or parse our own filtering syntax and just let users provide a single string.

**Comment by colindaniel** [comment]
Maybe we can brainstorm a way forward for the filtering sometime today? I agree with shree we should avoid getting into the weeds with our own unique filtering code. As always I’d like to check this against rsyncrosim also. I’m around today. Colin



________________________________

**Comment by shreeramsenthi** [comment]
That works for me, I'll be around all day! But if Katie's got it working as is though I think that's also fine for the current version. I don't know everyone else's priorities for the next few days.

**Comment by colindaniel** [comment]
Sure - if it’s working now and not holding you up Shree then let’s perhaps revisit next week instead? Katie - you decide?



________________________________

**Comment by katieb1** [comment]
That's interesting! I was just testing it out with the example-library from the helloworldSpatial package and it was working okay, but maybe in other use cases something weird is going on. Is that the Mariposa library you're using Shree? I can check it out today and see if I can reproduce your error.

As for filtering methods, I agree that it would be a lot simpler to do in Python, but the reason why we did it at the SyncroSim level was so that the methods would be identical between the Python and R APIs. However it would also be more efficient to do the filtering in Python since we wouldn't have to make a console call. Anyway, we can discuss all of this at some point. I'm free anytime today - perhaps we should discuss before I make any more changes to the filtering code?

**Comment by shreeramsenthi** [comment]
I'm afraid I'm working out of the CONUS library which is pretty huge, I'll pare it down as best I can and send it to you soon! And makes sense, I'll propose a meeting over teams!

**Comment by katieb1** [comment]
Okay! I just tried the filter_column on the Mariposa Library that Bronwyn sent me and it looks like setting `filter_column="StockGroupID=420"` or `filter_column="Timestep=2019"` is working fine for that Library. I wonder if there is something different about your CONUS wide Library that's throwing off the filter_column?

**Comment by shreeramsenthi** [comment]
yeah, that would be really helpful, thanks!

**Comment by shreeramsenthi** [comment]
Looks like I was just using the wrong version of SyncroSim. This PR is good to be merged in.

**Pull request merged**
